<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.lora</groupId>
    <artifactId>app-backend</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>App-backend</name>
    <description>ResQMesh Backend Microservices Aggregator</description>

    <modules>
        <module>backend/auth-service</module>
        <module>backend/device-service</module>
        <module>backend/sos_service</module>
        <module>backend/user-service</module>
    </modules>
</project>
